#!/usr/bin/env sh

set -vx --

function killit {
    trap - ALRM
    kill -ALRM $prog 2>/dev/null
    kill -9 $! 2>/dev/null && exit 0
}

function waitforit {
    trap "killit" ALRM
    sleep $1& wait
    kill -ALRM $$
}

waitforit $1& prog=$! ; shift ;
trap "killit" ALRM INT
"$@"& wait $!
if [[ "$(ps -ef | awk -v pid=$prog '$2==pid{print}{}')" != "" ]]; then
    kill -ALRM $prog
    wait $prog
fi
exit $?
