#!/usr/bin/env sh
# Rei <sovietspaceship/how>

if [ -z "$HOW_BROWSER" ]; then
    HOW_BROWSER='w3m'
fi

search_url='https://google.com/search?q='

function usage {
    echo "usage: how do(es) thing work"
    exit
}

function browse {
    $HOW_BROWSER "${search_url}$*"
}

function manpage {
    man $* 2>/dev/null
    if [ $? -eq 0 ]; then
        exit
    fi
}

if [ -z "$1" ]; then
    usage
fi

case $1 in 
    -h|--help)
        usage
        ;;
esac

if echo $@ | grep -E 'do(es)? .* work\??' >/dev/null; then
    thing=$(echo $@ | sed -e 's/\(.*\)work/\1/' | cut -d' ' -f2-)
    
    if [ "$thing" = "this " ]; then
        usage
    fi
    
    manpage "$thing"
fi

browse "how $@"
